### PR TITLE
(maint) Audit acceptance tests

### PR DESCRIPTION
**Pull request by johnduarte**
This PR cherry-picks the applicable commits from https://github.com/puppetlabs/pxp-agent/pull/794 to back-port the beaker tags for acceptance test risk and layer audit assessments.

### CODE REVIEW

**Comment by johnduarte** [comment]
Is this ok to merge?

**Comment by donoghuc** [comment]
jenkins please test this on centos6-64a,ubuntu1804-64a

**Comment by johnduarte** [comment]
The jenkins acceptance test job was rerun with the PCP_BROKER_REF set to 2018.1.x to bring it into parity with the regular acceptance pipeline job.

**Comment by johnduarte** [comment]
The acceptance test run is now green.  I think this can be merged.

**Pull request merged**
