### PR TITLE
(PCP-96) Remove unneeded config options and set correct defaults

### PR DESCRIPTION
**Pull request by ploubser**
- Remove interpreter module config parameter
- Set correct defaults for `puppet_bin` in pxp-module-puppet
- Add .bat file required to execute pxp-module-puppet on Windows.

### CODE REVIEW

**Comment by ploubser** [comment]
@Iristyle @parisiale Please check for sanity.

**Comment by parisiale** [comment]
:+1:

**Comment by Iristyle** [comment]
Building / testing locally - will drop a note when I've validated.

**Comment by Iristyle** [comment]
It looks like I'm having an issue loading the `pxp-module-puppet` module now:

```
2015-10-19 17:33:44.578676 TRACE puppetlabs.cpp_pcp_client.connector:337 - Executing callback for a message with 'http://puppetlabs.com/rpc_non_blocking_request' schema
2015-10-19 17:33:44.578676 INFO  puppetlabs.pxp_agent.action_request:63 - Validating non blocking request 4390bc5b-540d-44d3-abd8-55a9f7724bef by pcp://client01.example.com/puppet-api-test
2015-10-19 17:33:44.578676 DEBUG puppetlabs.pxp_agent.action_request:64 - Request 4390bc5b-540d-44d3-abd8-55a9f7724bef:
ENVELOPE: {"id":"4390bc5b-540d-44d3-abd8-55a9f7724bef","targets":["pcp://client02.example.com/agent"],"message_type":"http://puppetlabs.com/rpc_non_blocking_request","sender":"pcp://client01.example.com/puppet-api-test","expires":"2015-10-20T00:33:49.540Z"}
DATA: {"transaction_id":"7c8c4a82-7459-4611-9f29-6bf41c8b0c4a","notify_outcome":false,"module":"pxp-module-puppet","action":"run","params":{"env":[],"flags":[]}}
DEBUG: {"hops":[{"server":"pcp://broker.example.com/server","time":"2015-10-20T00:33:44.549Z","stage":"accepted"},{"server":"pcp://broker.example.com/server","time":"2015-10-20T00:33:44.553Z","stage":"accept-to-queue"},{"server":"pcp://broker.example.com/server","time":"2015-10-20T00:33:44.570Z","stage":"deliver"}]}
2015-10-19 17:33:44.578676 INFO  puppetlabs.pxp_agent.request_processor:193 - About to process non blocking request 4390bc5b-540d-44d3-abd8-55a9f7724bef by pcp: //client01.example.com/puppet-api-test, transaction 7c8c4a82-7459-4611-9f29-6bf41c8b0c4a
2015-10-19 17:33:44.578676 ERROR puppetlabs.pxp_agent.request_processor:203 - Invalid non blocking request 4390bc5b-540d-44d3-abd8-55a9f7724bef by pcp://client01.example.com/puppet-api-test, transaction 7c8c4a82-7459-4611-9f29-6bf41c8b0c4a: unknown module: pxp-module-puppet
2015-10-19 17:33:44.578676 INFO  puppetlabs.cpp_pcp_client.connector:247 - Creating message with id fdb8d4b8-46b6-4f33-b6ea-aee8ea0c1d56 for 1 receiver
2015-10-19 17:33:44.578676 DEBUG puppetlabs.cpp_pcp_client.connector:170 - Sending message of 405 bytes:
1size: 243 bytes - content: {"id":"fdb8d4b8-46b6-4f33-b6ea-aee8ea0c1d56","message_type":"http://puppetlabs.com/rpc_error_message","targets":["pcp://client01.example.com/puppet-api-test"],"expires":"2015-10-20T00:33:46.578676Z","sender":"pcp://client02.example.com/agent"}size: 151 bytes - content: {"transaction_id":"7c8c4a82-7459-4611-9f29-6bf41c8b0c4a","id":"4390bc5b-540d-44d3-abd8-55a9f7724bef","description":"unknown module: pxp-module-puppet"}
2015-10-19 17:33:44.578676 INFO  puppetlabs.pxp_agent.pxp_connector:75 - Replied to non blocking request 4390bc5b-540d-44d3-abd8-55a9f7724bef by pcp://client01.example.com/puppet-api-test, transaction 7c8c4a82-7459-4611-9f29-6bf41c8b0c4a, with an PXP error message
2015-10-19 17:34:00.187551 DEBUG puppetlabs.cpp_pcp_client.connector:429 - Sending heartbeat ping
2015-10-19 17:34:00.265674 DEBUG puppetlabs.cpp_pcp_client.connection:316 - WebSocket onPong event
2015-10-19 17:34:13.249633 TRACE puppetlabs.cpp_pcp_client.connector:337 - Executing callback for a message with 'http://puppetlabs.com/rpc_non_blocking_request' schema
2015-10-19 17:34:13.249633 INFO  puppetlabs.pxp_agent.action_request:63 - Validating non blocking request ba60a2c8-2e14-47ae-bc30-10a437633329 by pcp://client01.example.com/puppet-api-test
2015-10-19 17:34:13.249633 DEBUG puppetlabs.pxp_agent.action_request:64 - Request ba60a2c8-2e14-47ae-bc30-10a437633329:
ENVELOPE: {"id":"ba60a2c8-2e14-47ae-bc30-10a437633329","targets":["pcp://client02.example.com/agent"],"message_type":"http://puppetlabs.com/rpc_non_blocking_req
uest","sender":"pcp://client01.example.com/puppet-api-test","expires":"2015-10-20T00:34:18.210Z"}
DATA: {"transaction_id":"a6c91f63-9eb9-40a1-8709-905e4844282d","notify_outcome":false,"module":"pxp-module-puppet","action":"run","params":{"env":[],"flags":[]}}
DEBUG: {"hops":[{"server":"pcp://broker.example.com/server","time":"2015-10-20T00:34:13.221Z","stage":"accepted"},{"server":"pcp://broker.example.com/server","time":"2015-10-20T00:34:13.224Z","stage":"accept-to-queue"},{"server":"pcp://broker.example.com/server","time":"2015-10-20T00:34:13.238Z","stage":"deliver"}]}
2015-10-19 17:34:13.249633 INFO  puppetlabs.pxp_agent.request_processor:193 - About to process non blocking request ba60a2c8-2e14-47ae-bc30-10a437633329 by pcp: //client01.example.com/puppet-api-test, transaction a6c91f63-9eb9-40a1-8709-905e
4844282d
2015-10-19 17:34:13.249633 ERROR puppetlabs.pxp_agent.request_processor:203 - Invalid non blocking request ba60a2c8-2e14-47ae-bc30-10a437633329 by pcp://client01.example.com/puppet-api-test, transaction a6c91f63-9eb9-40a1-8709-905e4844282d: unknown module: pxp-module-puppet
2015-10-19 17:34:13.249633 INFO  puppetlabs.cpp_pcp_client.connector:247 - Creating message with id 5cd3531f-90ae-4cc2-bf78-978f605605c0 for 1 receiver
2015-10-19 17:34:13.249633 DEBUG puppetlabs.cpp_pcp_client.connector:170 - Sending message of 405 bytes:
1size: 243 bytes - content: {"id":"5cd3531f-90ae-4cc2-bf78-978f605605c0","message_type":"http://puppetlabs.com/rpc_error_message","targets":["pcp://client01.exa
mple.com/puppet-api-test"],"expires":"2015-10-20T00:34:15.249633Z","sender":"pcp
://client02.example.com/agent"}size: 151 bytes - content: {"transaction_id":"a6c91f63-9eb9-40a1-8709-905e4844282d","id":"ba60a2c8-2e14-47ae-bc30-10a437633329","
description":"unknown module: pxp-module-puppet"}
2015-10-19 17:34:13.265258 INFO  puppetlabs.pxp_agent.pxp_connector:75 - Replied to non blocking request ba60a2c8-2e14-47ae-bc30-10a437633329 by pcp://client01.example.com/puppet-api-test, transaction a6c91f63-9eb9-40a1-8709-905e4844282d, with an PXP error message
```

**Comment by kylog** [comment]
Woot! Merged.

**Pull request merged**
