### PR TITLE
Mergeup 1.9.x

### PR DESCRIPTION
**Pull request by donoghuc**

### CODE REVIEW

**Comment by donoghuc** [comment]
jenkins please test this on osx1014-64a,centos6-64a,ubuntu1804-64a,windows2016-64a

**Comment by johnduarte** [comment]
jenkins please test this on osx1014-64a,centos6-64a,ubuntu1804-64a,windows2016-64a

**Comment by johnduarte** [comment]
jenkins please test this on osx1014-64a,centos6-64a,ubuntu1804-64a,windows2016-64a

**Comment by johnduarte** [comment]
@donoghuc , I added a commit to restore the task_download test with appeared to have been overwritten by the run_script test somehow.  Can you review the current state of this file to ensure that it looks appropriate?

**Comment by donoghuc** [comment]
Oh man. That was totally my bad. It looks correct now. Sorry about that. The failure you are seeing on CRL seems like an issue. Let see if it passes in jenkins.

**Pull request merged**
