### PR TITLE
(PCP-405) Replace failover-ws-uri with broker-ws-uris

### PR DESCRIPTION
**Pull request by MikaelSmith**
The `broker-ws-uris` option is used in-place of `broker-ws-uri` to
specify multiple available brokers. The 1st will be used for initial
connection, and others will be used as failover brokers if it's
unavailable.

Also some minor fixes.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This will require a release of Horsewhisperer with https://github.com/puppetlabs/horsewhisperer/pull/46.

**Comment by MikaelSmith** [comment]
Working on adding more tests as well, I'm not 100% sure this works.

**Comment by parisiale** [comment]
:+1: 
I'll wait for Leatherman 0.7.3.

**Comment by MikaelSmith** [comment]
They're unrelated, don't need to wait for the Leatherman release.

**Pull request merged**
