### PR TITLE
Revert "(maint) Audit acceptance tests"

### PR DESCRIPTION
**Pull request by johnduarte**
Reverts puppetlabs/pxp-agent#794

### CODE REVIEW

**Comment by donoghuc** [comment]
jenkins please test this on redhat7-64a,windows2016-64a

**Comment by johnduarte** [comment]
jenkins please test this on redhat7-64a,windows2016-64a

**Comment by johnduarte** [comment]
jenkins please test this on redhat7-64a,windows2016-64a

**Comment by johnduarte** [comment]
jenkins please test this on redhat7-64a,windows2016-64a

**Pull request closed without merging**
