### PR TITLE
(PCP-494) Fix external module and pxp-module-puppet unicode handling

### PR DESCRIPTION
**Pull request by MikaelSmith**
Ensure the pxp-agent process locale is inherited when running external
modules, and specifically when pxp-module-puppet invokes Puppet. This
fixes issues with receiving non-ASCII characters from Puppet runs.

Depends on https://github.com/puppetlabs/leatherman/pull/199.

### CODE REVIEW

**Comment by parisiale** [comment]
👍 
Waiting for lth#199

**Comment by MikaelSmith** [comment]
Verified the acceptance test demonstrates prior failure and will succeed after this fix (with corresponding LTH fix).

**Comment by parisiale** [comment]
https://github.com/puppetlabs/pxp-agent/blob/master/modules/spec/unit/modules/puppet_spec.rb#L31 should be updated to also expect:
` :override_locale=>false`.

**Comment by MikaelSmith** [comment]
Updated, but blocked on https://github.com/puppetlabs/puppet-agent/pull/776.

**Comment by MikaelSmith** [comment]
Travis is lagging really badly.

**Comment by MikaelSmith** [comment]
This should be ready now, and I expect AppVeyor to pass any moment now.

**Comment by parisiale** [comment]
👍

**Pull request merged**
