### PR TITLE
(PCP-121) Explicitly export symbols

### PR DESCRIPTION
**Pull request by MikaelSmith**
Symbol visibility control can lead to greatly reduced library size on
Windows (all the suepr-long mangled names for C++ types and functions
can become surprisingly large), and also prevents performance
degradation on AIX. Add symbol exporting and annotate symbols that need
to be exported.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Depends on https://github.com/puppetlabs/horsewhisperer/pull/38.

**Comment by MikaelSmith** [comment]
Updated with a new release of HW.

**Comment by parisiale** [comment]
:+1: , but there's a CTest error

**Comment by MikaelSmith** [comment]
Oh, forgot to check Windows.

**Comment by MikaelSmith** [comment]
This isn't working on Windows yet, and I'm not sure why.

**Pull request closed without merging**
