### PR TITLE
Revert "(packaging) Prepare for 1.5.2 release"

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
Reverts puppetlabs/pxp-agent#579

Targeted at wrong branch

### CODE REVIEW

**Comment by ScottGarman** [comment]
:+1:

**Comment by kurtwall** [comment]
My thumb is the second one. I'll merge after travis and appveyor

**Comment by MikaelSmith** [comment]
Should've just dealt with the conflict on merge-down, this revert is making merging stable -> master painful.

**Comment by kurtwall** [comment]
😢

**Pull request merged**
