### PR TITLE
(PA-2183) Update acceptance tests to work with Beaker 4

### PR DESCRIPTION
**Pull request by ekinanp**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
If this works, cool.

**Comment by MikaelSmith** [comment]
jenkins please test this

**Comment by ekinanp** [comment]
Going to do a quick ad-hoc run of all this before a merge

**Comment by ekinanp** [comment]
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/__experimental/job/experimental_puppet-agent-extra_puppet-agent-integration-suite_adhoc-1.10.x/2/ shows a passing ad-hoc run, so this is good to go.

**Comment by ekinanp** [comment]
Targetting this at 1.9.x instead

**Pull request merged**
