### PR TITLE
(maint) Add AppVeyor and Travis CI

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by Iristyle** [comment]
Looks like we need a rebase @MikaelSmith 

This was ready to go otherwise, right?

**Comment by MikaelSmith** [comment]
It was, I'll rebase.

**Comment by MikaelSmith** [comment]
Added the modules rspec run, but I don't have the same control over Ruby versions. rvm is only available in a Ruby build VM.

**Comment by Iristyle** [comment]
Hmm - that's a bummer wrt Ruby versions.  It looks like they have `1.9.3-p551` installed by default in Travis - but we'll only ever run the module / module tests against `2.1.x+`.

This probably isn't worth spending a ton of time on, but it looks like you might still be able to switch Ruby versions by hand - http://rubies.travis-ci.org/usage

Precompiled / downloadable Ruby packages are available at http://rubies.travis-ci.org/

**Comment by MikaelSmith** [comment]
I'll give it a try.

**Comment by Iristyle** [comment]
"Disallowing packages: ruby-2.1.7" with your approach.

What I meant was calling `install-ruby` - which I think Travis has installed (source at https://github.com/postmodern/ruby-install)

That usage page had proposed that Travis can use `ruby-install --binary -M https://rubies.travis-ci.org/ ruby 2.1.1` for instance, but that PR at https://github.com/postmodern/ruby-install/pull/138 wasn't ever merged.

**Comment by MikaelSmith** [comment]
Ah yeah, that looks like it might not work without sudo yet.

**Comment by MikaelSmith** [comment]
Dropped the last commit, this is probably ok.

**Pull request merged**
