### PR TITLE
(PCP-660) Add test case for connecting to a PCP v1 endpoint

### PR DESCRIPTION
**Pull request by MikaelSmith**
Adds a test case that verifies sending and receiving messages over a PCP
v1 connection.

[skip ci]

### CODE REVIEW

**Comment by nicklewis** [comment]
Should this test have a `teardown` step that reconnects the agent back to v2?

**Comment by MikaelSmith** [comment]
That seems useful, yes. I'm pretty sure every test actually does its own configuration and restarts pxp-agent, but luckily that doesn't take too long. The benchmark for whether we need teardown would be invalid_ssl_config.rb, which does include it, so I'll add some.

**Comment by MikaelSmith** [comment]
Updated.

**Comment by MikaelSmith** [comment]
Tested with
```
be rake ci:test:aio SHA=e5645317f977e322492b526728084dca6ff9db27 TEST=tests TEST_TARGET=centos7-64a
```

**Comment by nicklewis** [comment]
:+1:

**Pull request merged**
