### PR TITLE
(PCP-334) Defer to Leatherman on imbuing a locale

### PR DESCRIPTION
**Pull request by MikaelSmith**
This follows Leatherman's support for disabling locales on platforms
that don't have solid implementations, rather than hard-coding the
platforms.

This also bumps the leatherman we test against to 0.4.2 to pull in that
behavior.

Related to https://github.com/puppetlabs/facter/pull/1281. Hold off merging until Leatherman 0.4.2 is released.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@parisiale this will be needed for the next puppet-agent release.

**Comment by MikaelSmith** [comment]
@branan I think all the dependencies are in.

**Comment by branan** [comment]
:+1: from me, looks good. @parisiale any complaints before we hit the button here?

**Comment by MikaelSmith** [comment]
I'm going to make this a ticket.

**Comment by MikaelSmith** [comment]
Updated with ticket number, running through CI again.

**Comment by MikaelSmith** [comment]
Passed.

**Pull request merged**
